### ISSUE TITLE
是否有开源计划呢？

### ISSUE THREAD

**Issue by zer0yu** [veo/vshell#1]
如题

**Comment by veo** [comment]
暂时不考虑开源，但是后续可能会放出编译好的文件，目前还没写完有很多问题，所以没有放出

**Comment by veo** [comment]
> 如题

暂时不考虑开源，但是后续可能会放出编译好的文件，目前还没写完有很多问题，所以没有放出

**Comment by zer0yu** [comment]
get, 期待
