### ISSUE TITLE
可否只用一个远控程序不用配置文件~

### ISSUE THREAD

**Issue by Gofreedom0** [veo/vshell#11]
今天发现vshell更新了，下载程序使用tar -zxvf vshell.tar.gz解压不小心覆盖了之前的配置文件，导致目标全部丢失。。。

问下有啥补救的办法么~~之前改过配置文件的web端口和密钥（密钥忘记）

**Comment by veo** [comment]
最近更新了协议的格式，新版本不兼容旧版本。。。

还是有机会重新上线。需要下载你之前用的旧版本，但必须端口和密钥是跟之前一样的。。。他就会重新上线，密钥忘记那就没办法了。

**Comment by veo** [comment]
没关机的话，你可以试试linux文件恢复找找密钥……

**Comment by veo** [comment]
是配置文件里的public_key不记得了是吧？我帮你看看代码有没有机会

**Comment by veo** [comment]
你发我加
