### ISSUE TITLE
win11 插件打不开 是灰色按钮

### ISSUE THREAD

**Issue by dd2008** [veo/vshell#13]
![QQ截图20220910124157](https://user-images.githubusercontent.com/70691142/189469050-105fabf4-3c9e-41d3-aa48-35043b2e74f6.png)

**Comment by veo** [comment]
您好，现在已经弃用蚁剑的链接方式，直接使用web进行管理

**Comment by dd2008** [comment]
有下载地址吗

**Comment by veo** [comment]
https://github.com/veo/vshell/releases

**Comment by dd2008** [comment]
默认账号密码是什么
