### ISSUE TITLE
测试了下，发现执行shell命令之后，会多一个bash -i

### ISSUE THREAD

**Issue by y35uishere** [veo/vshell#15]
每次打开命令，都会出现一个bash -i

这样打开多次，就一堆bash -i

能不能自动关闭呢？

或者加个按钮，一键关闭。

这些bash -i都是主进程派生的。

**Comment by veo** [comment]
是3.2.0版本吗？刚发的新版

**Comment by y35uishere** [comment]
哦，我测试的3.1.0
