### ISSUE TITLE
【优化显示】客户端生成页面

### ISSUE THREAD

**Issue by y35uishere** [veo/vshell#18]
服务端地址，服务端端口
都是再模板里面写死的，很不方便，每次都得自己手打

可以读取配置文件形式展示，这样方便一点

bridge_port=
bridge_ip=

**Comment by veo** [comment]
可能存在端口需要被转发的情况，所以保留了填写步骤

且可方便生成其他服务端的程序

**Comment by veo** [comment]
3.3.0 已支持
