### ISSUE TITLE
【优化】服务端占用cpu非常高

### ISSUE THREAD

**Issue by y35uishere** [veo/vshell#19]
当上线机器少的时候没什么感觉
当上线机器多了，cpu占用和内存占用非常高，达到150%

4核机器根本扛不住。

希望有可能的话优化下

**Comment by veo** [comment]
感谢反馈，我到时候测试一下

**Comment by veo** [comment]
![top](https://user-images.githubusercontent.com/38176360/194799731-4d81d658-246a-4144-b69b-412c79c96d68.png)

测试3台机器半小时并未发现占用高的情况，方便描述一下你使用了什么功能吗？

**Comment by veo** [comment]
问题已找到，断开连接太长后，KCP协议无法重新建立隧道，陷入死循环，目前没找到好的解决方式
3.3.0协议进行了修改，可能不会再出现这个问题
