### ISSUE TITLE
russian language

### ISSUE THREAD

**Issue by b4sh1t1** [veo/vshell#2]
Hi,

I'm offering support for Russian language; i'm ready to work on this but i need author support if accepted.

**Comment by veo** [comment]
> Hi,
> 
> I'm offering support for Russian language; i'm ready to work on this but i need author support if accepted.

https://github.com/AntSwordProject/antSword
vshell rely on AntSword Plugins，vshell and antSword support English but not Russian
![image](https://user-images.githubusercontent.com/38176360/136015974-bad159af-41fb-453a-a196-81c16dd88179.png)

If you want support Russian ,you need Issues antSword first ,if AntSword support russian,vshell will

Thanks for opening the issue

**Comment by b4sh1t1** [comment]
Thanks for your replay; ok how can i contact you in wechat ? i have some question in private please.

**Comment by veo** [comment]
> Thanks for your replay; ok how can i contact you in wechat ? i have some question in private please.

you can see 

https://gist.githubusercontent.com/veo/be21f4221d6534137366c791673e1b76/raw/f1bd9f03cbe5c1a144e639fee4e2c5b9d8bff082/gistfile1.txt

soon delete

**Comment by b4sh1t1** [comment]
thanks; you can delete.
