### ISSUE TITLE
【bug】当以root上线之后，执行的命令

### ISSUE THREAD

**Issue by y35uishere** [veo/vshell#21]
当以root上线之后，执行的命令
都会记录再bash_HISTORY

应该再执行命令之前自动unset

**Comment by veo** [comment]
防止滥用，不会隐藏

**Comment by y35uishere** [comment]
哦，那太可惜了。没有源码，也没办法改。
如果拿来当主机管理的话，这种产品还是很多的。
没有这个会让好产品变的鸡肋了
