### ISSUE TITLE
一些优化建议

### ISSUE THREAD

**Issue by badboycxcc** [veo/vshell#25]
1. 截屏记录能否保存并在页面显示，刷新页面后需要重新截屏。
2. 历史命令记录能否保存。
3. 能否增加https协议隧道。
4. 感觉Nps功能多余，上线后会默认创建Nps文件，可以选择关闭这个功能。

**Comment by veo** [comment]
好提议，最后一个是删掉npk文件吧。

**Comment by badboycxcc** [comment]
> 好提议，最后一个是删掉npk文件吧。

是的，上线后默认创建Npk文件。

**Comment by veo** [comment]
建议4已修复，其他功能需要再等等

**Comment by xiaokul** [comment]
方便源码公开吗

**Comment by badboycxcc** [comment]
这个我问了，不开源。

**Comment by veo** [comment]
3.4.0 都已变相支持相关功能，关闭issues

**Comment by badboycxcc** [comment]
等到更新，继续测试
