### ISSUE TITLE
启动很多子进程，不会自己退出吗？

### ISSUE THREAD

**Issue by badboycxcc** [veo/vshell#26]
如图所示
<img width="265" alt="截屏2022-10-30 下午12 44 15" src="https://user-images.githubusercontent.com/72059221/198863015-2b28f8a7-328e-4ce4-886e-d3fbfd1b5599.png">

**Comment by veo** [comment]
某些情况下是的，Linux以前解决过这个问题，windows没有特别关注

关闭命令控制台时可以尝试先使用exit命令关闭进程

没彻底改好的原因是框架已经定了，没有预留退出进程的接口

**Comment by veo** [comment]
3.3.0 版本已修复
