### ISSUE TITLE
大佬能不能帮我看看这个是怎么回事

### ISSUE THREAD

**Issue by 1098346640** [veo/vshell#3]
![U%3CS$X7V3C UEXZ$HZ}N@U](https://user-images.githubusercontent.com/51485740/151691827-a062ace7-5803-45c1-ade7-ef405def6c17.png)
我用中国蚁剑连的shell（应该是没有waf）然后虚拟终端提示ret=127，是不是bash被禁了，要怎么办呢
![`MPZZY%14E8 2Y86T~HCJU](https://user-images.githubusercontent.com/51485740/151691867-8d91b64b-9391-47c1-b7dd-335d028e9f62.png)
只支持这些函数

**Comment by veo** [comment]
> ![U%3CS$X7V3C UEXZ$HZ}N@U](https://user-images.githubusercontent.com/51485740/151691827-a062ace7-5803-45c1-ade7-ef405def6c17.png)
> 我用中国蚁剑连的shell（应该是没有waf）然后虚拟终端提示ret=127，是不是bash被禁了，要怎么办呢
> ![`MPZZY%14E8 2Y86T~HCJU](https://user-images.githubusercontent.com/51485740/151691867-8d91b64b-9391-47c1-b7dd-335d028e9f62.png)
> 只支持这些函数

此问题与本软件无关，其他插件问题请自行查阅相关资料
