### ISSUE TITLE
多级代理/不出网机器上线 有计划吗？

### ISSUE THREAD

**Issue by k-fire** [veo/vshell#38]

**Comment by veo** [comment]
有的
目前有3个方案正在研究，要些时间
1.正向连接
2.DNS或其他协议
3.ebfp

**Comment by k-fire** [comment]
多级代理我用过[stowaway](https://github.com/ph4ntonn/Stowaway)，感觉挺好可以参考一下，感谢分享工具

**Comment by k-fire** [comment]
遇到个问题：编辑文件时需要删除txt中全部内容时，OK按钮灰色

**Comment by veo** [comment]
> 遇到个问题：编辑文件时需要删除txt中全部内容时，OK按钮灰色

感谢反馈，临时可以先加一个空格保存

**Comment by veo** [comment]
> Linux 服务端出现这样的报错
> ![image](https://user-images.githubusercontent.com/40354487/270346393-476a51b7-cfad-4baa-834d-56bdfc4072ad.png)

这是浏览器开了F12调试模式尝试调用map文件，而本身并没有这些map文件，是正常日志

**Comment by k-fire** [comment]
> > Linux 服务端出现这样的报错
> > ![image](https://user-images.githubusercontent.com/40354487/270346393-476a51b7-cfad-4baa-834d-56bdfc4072ad.png)
> 
> 这是浏览器开了F12调试模式尝试调用map文件，而本身并没有这些map文件，是正常日志

谢谢指导

**Comment by k-fire** [comment]
在kali linux下测试，运行客户端后开启自启动，随后进行关机操作，当前会话会一直显示在线状态（卡住，控制台无关闭日志），再启动kali，自启动服务正常，随着而来的是，在命令控制台中，若选中卡住”正常“状态的会话则会白屏，再选择其他正常的会话也会一直白屏，除非刷新页面再选择正常会话。
![动画](https://github.com/veo/vshell/assets/40354487/0a4a11fc-c895-42d2-a88d-afa38457d14e)

**Comment by k-fire** [comment]
linux 自启动有时候获取不到内网IP
![image](https://github.com/veo/vshell/assets/40354487/d7aad06c-a822-4694-9eea-12e39afd4623)

**Comment by veo** [comment]
> 在kali linux下测试，运行客户端后开启自启动，随后进行关机操作，当前会话会一直显示在线状态（卡住，控制台无关闭日志），再启动kali，自启动服务正常，随着而来的是，在命令控制台中，若选中卡住”正常“状态的会话则会白屏，再选择其他正常的会话也会一直白屏，除非刷新页面再选择正常会话。
> ![动画](https://user-images.githubusercontent.com/40354487/270430296-0a4a11fc-c895-42d2-a88d-afa38457d14e.gif)

感谢反馈，这个应该是kcp模式的吧，这个没办法，kcp只能靠心跳监控状态，等60s就正常了

**Comment by veo** [comment]
> 在锐捷路由器下使用蚁剑命令终端执行linux arm64客户端 ，然后重启服务端有概率会导致客户端程序直接退出。另外在开启用户注册后，注册页面logo似乎有点位置偏差。

注册功能暂时没开放，arm客户端维护不过来一般不会过多关注

**Comment by veo** [comment]
> linux 自启动有时候获取不到内网IP
> ![image](https://user-images.githubusercontent.com/40354487/270452038-d7aad06c-a822-4694-9eea-12e39afd4623.png)

可能是不同系统的bug？麒麟获取不到还是重启才有问题？

**Comment by k-fire** [comment]
> 感谢反馈，这个应该是kcp模式的吧，这个没办法，kcp只能靠心跳监控状态，等60s就正常了

TCP模式  会一直卡死  手动删除会话也会卡很长时间

**Comment by k-fire** [comment]
> > linux 自启动有时候获取不到内网IP
> > ![image](https://user-images.githubusercontent.com/40354487/270452038-d7aad06c-a822-4694-9eea-12e39afd4623.png)
> 
> 可能是不同系统的bug？麒麟获取不到还是重启才有问题？

重启时  自启动的时候获取不到

**Comment by k-fire** [comment]
有出现这样的情况，windows10加入开机启动后，可以看到服务已被添加，实际开机时能看到有新会话连接，但无法长时间保持。

**Comment by veo** [comment]
> 有出现这样的情况，windows10加入开机启动后，可以看到服务已被添加，实际开机时能看到有新会话连接，但无法长时间保持。

后续开机启动功能会被完全替换，因为过不了杀软和权限问题

**Comment by k-fire** [comment]
> > 有出现这样的情况，windows10加入开机启动后，可以看到服务已被添加，实际开机时能看到有新会话连接，但无法长时间保持。
> 
> 后续开机启动功能会被完全替换，因为过不了杀软和权限问题

那准备怎么做权限维持呢？

**Comment by veo** [comment]
> > > 有出现这样的情况，windows10加入开机启动后，可以看到服务已被添加，实际开机时能看到有新会话连接，但无法长时间保持。
> > 
> > 
> > 后续开机启动功能会被完全替换，因为过不了杀软和权限问题
> 
> 那准备怎么做权限维持呢？

定时任务或者别的吧，现在的开机启动有点不好用

**Comment by k-fire** [comment]
期待

**Comment by k-fire** [comment]
> > > > 有出现这样的情况，windows10加入开机启动后，可以看到服务已被添加，实际开机时能看到有新会话连接，但无法长时间保持。
> > > 
> > > 
> > > 后续开机启动功能会被完全替换，因为过不了杀软和权限问题
> > 
> > 
> > 那准备怎么做权限维持呢？
> 
> 定时任务或者别的吧，现在的开机启动有点不好用

服务启动项应该是需要服务类程序，普通的应用程序不行，需要符合系统服务规范。
如果是做成计划任务，要考虑一下进程互斥，不然上线一堆机器。
也可以选择多种权限维持办法，windows和linux服务、启动项、计划任务，
另外有几个小建议：屏幕截屏
不成功时返回一张默认图片会更好些，现在默认那个失败的图标有点难看；客户端生成可以多支持一些类型吗？比如mips等；supershell的一些功能也可以借鉴下，比如内存加载等。

**Comment by veo** [comment]
> > > > > 有出现这样的情况，windows10加入开机启动后，可以看到服务已被添加，实际开机时能看到有新会话连接，但无法长时间保持。
> > > > 
> > > > 
> > > > 后续开机启动功能会被完全替换，因为过不了杀软和权限问题
> > > 
> > > 
> > > 那准备怎么做权限维持呢？
> > 
> > 
> > 定时任务或者别的吧，现在的开机启动有点不好用
> 
> 服务启动项应该是需要服务类程序，普通的应用程序不行，需要符合系统服务规范。 如果是做成计划任务，要考虑一下进程互斥，不然上线一堆机器。 也可以选择多种权限维持办法，windows和linux服务、启动项、计划任务， 另外有几个小建议：屏幕截屏不成功时返回一张默认图片会更好些，现在默认那个失败的图标有点难看；客户端生成可以多支持一些类型吗？比如mips等；supershell的一些功能也可以借鉴下，比如内存加载等。

内存加载和插件功能已经有了，但是还没公开。权限维持有时间再搞一下，还没想好

截屏的图片有点难看吗，哈哈

客户端类型因为有stager模式，多一个客户端类型就多一个要维护测试的，还是优先考虑协议扩充

追求稳定吧，一项一项来。目前内存加载和插件功能测试了一个多月了，我觉得才差不多完成了一半。代码好写，但是我觉得易用性和稳定性要更关键

**Comment by veo** [comment]
![image](https://github.com/veo/vshell/assets/38176360/360f379a-04da-463e-bcdc-32025747f955)

**Comment by k-fire** [comment]
主机多次开关机或者网络因素导致会话数增多，给主机弄个唯一标识做成分组会不会直观一些，主机数量一多导致翻页查询比较麻烦、不好区分

**Comment by veo** [comment]
> 主机多次开关机或者网络因素导致会话数增多，给主机弄个唯一标识做成分组会不会直观一些，主机数量一多导致翻页查询比较麻烦、不好区分

重复上线这个问题，我还是觉得应该对标的进程，一个进程一个会话

分组确实可以，但是前端没想好怎么设计，我前端不太会也看得出来

**Comment by veo** [comment]
v4.2.0 已支持ebpf、正向上线、代理链 功能，不出网的问题应该可以完美解决
