### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by Saysomethings** [veo/vshell#4]
![issus](https://user-images.githubusercontent.com/84262520/153116724-2e8346b8-744b-460c-86b4-df0e1697c32d.png)

**Comment by veo** [comment]
> ![issus](https://user-images.githubusercontent.com/84262520/153116724-2e8346b8-744b-460c-86b4-df0e1697c32d.png)

我看不出来是什么问题，请描述的详细一点。

**Comment by Saysomethings** [comment]
![图片](https://user-images.githubusercontent.com/84262520/153120888-304d40dc-d760-427d-9cd9-2cff9f1e5784.png)
无法加载插件

**Comment by veo** [comment]
> ![图片](https://user-images.githubusercontent.com/84262520/153120888-304d40dc-d760-427d-9cd9-2cff9f1e5784.png)
> 无法加载插件

蚁剑连接类型 CUSTOM，如乱码编码类型可选GBK
