### ISSUE TITLE
发现一个问题：创建开机自启动服务老是失败

### ISSUE THREAD

**Issue by dracodong** [veo/vshell#44]
<img width="864" alt="image" src="https://github.com/veo/vshell/assets/36252282/12c7ba21-1375-4420-b645-feb7873f510c">
![123](https://github.com/veo/vshell/assets/36252282/7d7db098-2a30-449d-832b-fae78bbd5d79)

**Comment by veo** [comment]
stager会有这个问题，如需开机启动暂时使用stagerless，后续版本会修复

**Comment by dracodong** [comment]
谢谢老铁 辛苦了

**Comment by veo** [comment]
v4.2.0已修复
