### ISSUE TITLE
用了一段时间，有几个地方不是很方便。

### ISSUE THREAD

**Issue by Little-Potato01** [veo/vshell#48]
1，在线 和 离线 最好分页显示，混合在一起 多了看起来混乱。上一百台测试机，结果一天时间 离线和在线混合8千多 ID。

2，windows系统的服务启动不好用，开机各种问题服务启动不了，还弹出提示窗口，我测试注册表启动各个win系统版本都可以。
注册表添加开机启动：
reg add hklm\software\microsoft\windows\CurrentVersion\run /v ma /t reg_sz /d C:\1.exe /f

3，客户端重复运行会重复上线，自己做了 注册表添加开机启动 后，测试机多用户登录后重复上线。希望做成不能重复运行的客户端。

4，离线 ID太多，一个个删除好难，请添加一键删除离线。

**Comment by veo** [comment]
授权测试和管理不会出现重复上线这么多的情况。请立即停止你的攻击行为，严格准守网络安全法。

本工具仅面向合法授权的企业管理行为，在使用本工具进行主机管理时，您应确保该行为符合当地的法律法规，并且已经取得了足够的授权。

如您在使用本工具的过程中存在任何非法行为，您需自行承担相应后果，作者将不承担任何法律及连带责任。

**Comment by Little-Potato01** [comment]
你好，我不是搞黑产的，我是机房的管理人员，我用了一台母机装了几百各种系统的vps 测试的，
这个  在线 和 离线 分页显示，是很有必要的。
