### ISSUE TITLE
群二维码过期了

### ISSUE THREAD

**Issue by xiaokul** [veo/vshell#54]
你好，微信群二维码过期了

**Comment by dracodong** [comment]
是的

**Comment by veo** [comment]
二维码会在下一次版本更新时更新

**Comment by veo** [comment]
已更新二维码，7天以后失效

**Comment by xiaokul** [comment]
好的，谢谢

**Comment by xiaokul** [comment]
你好，我扫了之后还是过期

**Comment by xiaokul** [comment]
![Uploading Screenshot_20240310_004632.jpg…]()

**Comment by xiaokul** [comment]
![Screenshot_20240310_004624](https://github.com/veo/vshell/assets/119649220/43e6281b-8941-43ef-8281-ac078966cf30)

**Comment by xiaokul** [comment]
![Uploading Screenshot_20240310_004632.jpg…]()

**Comment by veo** [comment]
又更新了

**Comment by xiaokul** [comment]
已加群，麻烦了

**Comment by 9527952777** [comment]
群200人满了，师傅拉一拉

**Comment by veo** [comment]
> 群200人满了，师傅拉一拉，微信号：y9981666666

建了个二群

**Comment by 9527952777** [comment]
> > 群200人满了，师傅拉一拉，微信号：y9981666666
> 
> 建了个二群

师傅，来个二维码，我直接进

**Comment by veo** [comment]
> > > 群200人满了，师傅拉一拉，微信号：y9981666666
> > 
> > 
> > 建了个二群
> 
> 师傅，来个二维码，我直接进

已经更新二维码了
