### ISSUE TITLE
选择客户端执行命令提示This account is currently not available

### ISSUE THREAD

**Issue by Gofreedom0** [veo/vshell#6]
使用linux客户端上线时选择客户端命令执行提示：This account is currently not available
目标用户为tomcat

并且测试过程中发现直接以./客户端这样执行会卡住，不会后台运行，需要用nohup辅助进行后台运行

**Comment by veo** [comment]
> 使用linux客户端上线时选择客户端命令执行提示：This account is currently not available 目标用户为tomcat
> 
> 并且测试过程中发现直接以./客户端这样执行会卡住，不会后台运行，需要用nohup辅助进行后台运行

第一个问题我觉得应该是你环境的问题，没能执行成功

第二个问题。之前是支持Linux直接后台运行的，但是有些系统版本可能会有问题，所以删除了这个功能。综合考虑下决定采用nohup后台运行的方式

**Comment by Gofreedom0** [comment]
不知道啥原因.....我没执行，选择客户端的时候提示的，目标用户权限为tomcat，不知道是不是bash环境变量原因。我用其他远控程序可以，并且能交互式~~
![image](https://user-images.githubusercontent.com/22413346/175189736-77435796-eb23-4aa7-96b9-63f178388b89.png)

**Comment by veo** [comment]
不过你这点提醒了我，不能完全只做交互shell。。。有些用户可能权限不够

**Comment by Gofreedom0** [comment]
期待更新

**Comment by veo** [comment]
会的，我自己也用，会随时改代码
