### ISSUE TITLE
创建文件bug

### ISSUE THREAD

**Issue by Gofreedom0** [veo/vshell#7]
web界面创建文件的时候文件创建失败~~
![image](https://user-images.githubusercontent.com/22413346/175754619-21cb03b5-5e1d-4265-bfc5-81a327ea994f.png)
蚁剑一样
![image](https://user-images.githubusercontent.com/22413346/175754662-d67705a3-d0f2-4be9-a539-b55651144dd2.png)
wget正常

**Comment by veo** [comment]
感谢提交issues，这个bug会在下个版本修复

**Comment by Gofreedom0** [comment]
好的，作者这个是真的好用，已经准备抛弃其他远程控制了

**Comment by veo** [comment]
> 好的，作者这个是真的好用，已经准备抛弃其他远程控制了

谢谢认可。
软件后续会不断更新完善

**Comment by Gofreedom0** [comment]
好的，等待更新。
可否在下个版本增加-客户端生成的时候支持选择协议上线，或者TCP上线后支持一键升级成udp协议

**Comment by veo** [comment]
> 好的，等待更新。
> 可否在下个版本增加-客户端生成的时候支持选择协议上线，或者TCP上线后支持一键升级成udp协议

这个我有试过。客户端好弄，服务端不好弄我就先没加这个功能，有时间我再试一下

**Comment by Gofreedom0** [comment]
好的
